### ISSUE TITLE
Equirectangular panorama never have z-values in imageToGroundPanorama

### ISSUE THREAD

**Issue by SoftFeta** [Esri/oriented-imagery#11]
Despite "exposure points" are given in 3D (i.e. possessing z-values), the function `imageToGroundPanorama` in `viewer.js` do not calculate them.
Even given the `z-axis of the exposure point`, `HFOV`, `heading`, `pitch`, `roll`, `depth` from the depth map, the distance above ground is always NaN, because the resultant point is hard-wired into 2D.
You can definitely calculate the z if you have the values above. First you find the tilt of the current heading using the original `tilt` and `heading`, then you add `the angle between the origin and the point`. Since you have the new angle and the depth, you now have `depth*Math.atan2(newAngle)`. More on this later.

**Comment by SoftFeta** [comment]
In case of a equirectangular panorama:
Indeed, `this.measurementInfo.points[0]` is the lower point of the measurement while `this.measurementInfo.points[1]` is the upper point. `this.measurementInfo.points[*][0]` is the y-offset from the centre of the image, ranges from (-90, 90); while `this.measurementInfo.points[*][1]` is the x-offset from the centre of the image, ranges from (-180, 180). `this.measurementInfo` is always 90deg expressed in radians.
Get the tilt and heading from `this.selectedFeatureAttributes.camheading`, `this.selectedFeatureAttributes.campitch`, `this.selectedFeatureAttributes.camroll`.

`this.selectedFeatureAttributes.point_z` is not needed.

**Comment by SoftFeta** [comment]
Obviously, `this.imageToGroundPanorama` should only apply to the first point (the measuring base), not the second point. The second point has nothing to do with the depth map, as it is floating in the air!

**Comment by kushu493** [comment]
Hi Alex,

We are working on it. Can you please share some sample data so that we can reproduce the issue that you are facing.

Thank You.

**Comment by SoftFeta** [comment]
Kushagra,
Thanks for the reply. Unfortunately my only available test data was copyrighted by the client. I cannot share the whole site but some screenshots.

For example, we want to measure the height of some thin objects like a lamppost. I don't think we need to put the second point precisely on the lamppost (point B), which is pretty hard. Instead, we should be able to measure the distance by placing the second point on A, which suspends mid-air. Yet, the datum at point A is nil, therefore the result of `this.imageToGroundPanorama` is erroneous. The feature's name is Height **Above Ground** after all.
<img src="https://drive.google.com/uc?export=view&id=1eTAAI2B8PGuAjdx2e2L5mstZ45O30DKO" width="500px" />
<hr>
We want to measure the automobile. But since in the photo's perspective, the road and the automobile overlap. We even can't place the second slightly above the car (point B), as it will mark the road.
<img src="https://drive.google.com/uc?export=view&id=1cCRDW0OfAiVUgXxf_PwSeqRpmavybfhm" width="500px" />
<hr>
Besides, we cannot measure anything non-existent, like planned development like future buildings, barriers and sculptures.

The below line in `viewer.js`, a is hard-coded to be a 2-element array:
```js
v < 0 && (v += 360), v > 360 && (v -= 360), a = [this.selectedFeatureGeometry.x + h * Math.sin(v * Math.PI / 180), this.selectedFeatureGeometry.y + h * Math.cos(v * Math.PI / 180)]
```
That means no z-values are present. Thus, the **Location** measurement is missing the Z coordinate.
<hr>
When one create a catalogue using the ArcGIS Pro OIC plugin, even if the active map is a 3D scene, the points are hard-coded to be 2D. Even if the photo has a `GPSAltitude` EXIF field, the plugin does not read the value.
<img src="https://drive.google.com/uc?export=view&id=13HoCL2JIWFeGSqcyneGnlOzrbCSZZHC5" width="500px" />
One has to drag the exposure points from 2D to 3D, manually enables their z-values, and change the path to the new exposure points.
Indeed, the viewer is **able** to read the z-values of these photos after the onerous procedure, but they are currently useless.

**Comment by SoftFeta** [comment]
By the way,

(cf. #15) you can snap the green diamond indicator to the buildings with the new z value

**Comment by priya4991** [comment]
@SoftFeta please update the widget with the new version and let us know if you face any issues.
Thanks!

**Comment by SoftFeta** [comment]
Discussion in #24 .
