### ISSUE TITLE
Blue and Alpha are not used but the depth map has to be RGBA(?) Makes everything slower

### ISSUE THREAD

**Issue by SoftFeta** [Esri/oriented-imagery#17]
May I ask why the depth maps are required to be RGBA?

This is from `loadDepthImage` from `viewer.js` :

```js
for (var l = 0; l < Object.keys(this.depthInfo.pixels).length; l++)
for (var c = n.getImageData(a * l, 0, a, h.height), m = 0; m < c.data.length; m += 4) e = c.data[m] >> 6 << 1, s = ((63 & c.data[m]) << 8 | c.data[m + 1]) << e, this.depthInfo.pixels[l].push(s / 1e3);
this.depthImage = !0, this.depthInfo.isLoading = !1, I.set(this.depthBtn, "display", "inline"), this.domNode.getElementsByClassName("oi-imageViewer")[0].removeChild(h)
```

If I am not mistaken, `c.data[m]` is the red channel and `c.data[m + 1]` is the green channel. That means the blue and alpha channel are unused. It doubles the data and slows down the load process of the image (and the **generation** of depth images). And how should one express decimal places of lengths? Thanks.

**Comment by kushu493** [comment]
Hi Alex,

We don't recommend users to provide depth maps in png format. We support png format for one of our partners specifically.

Can you please close this issue?

**Comment by SoftFeta** [comment]
Sure. Please update the docs.
