### ISSUE TITLE
Zooming issues

### ISSUE THREAD

**Issue by SoftFeta** [Esri/oriented-imagery#21]
There are two zooming issues.
The first one is a serious one. Zooming in your `libpannellum.js` is directly tied to the maximum FOV, which is in turn tied to FarDistance. In Pannellum (v2.5), zooming is simply magnification, it neither depends on or modifies the FOV. Indeed, the buttons do nothing (except the behaviour in #18) when the OIC window is *large enough*, say above 600x600.
The screenshot sums the first issue up :
<img src="https://drive.google.com/uc?export=view&id=1aV4YZKSAAZVYoppCtb3BFMo9MnwfGhkH" width="600px" />
Magnification is essential since without it measuring will not be accurate. At the end of the road, the depth values are packed together. Deviation by a single pixel may change a lot. Also, zooming is among the most common features.

The second one is #18. When the OIC window is *large enough*, say above 600x600, pressing "Zoom In" actually zooms out once. Then the buttons simply do nothing.

<img src="https://drive.google.com/uc?export=view&id=1HGKaXUNVM_nXJHyo5E2nOa7IbqckiMY-" width="600px" />

 Thanks for all the hard work.

**Comment by priya4991** [comment]
@SoftFeta please update the widget with the new version and let us know if you face any issues.
Thanks!

**Comment by SoftFeta** [comment]
Thanks, Priya! Superb work
