### ISSUE TITLE
Distance measurement tool always shows `NaNm ± NaN`

### ISSUE THREAD

**Issue by SoftFeta** [Esri/oriented-imagery#28]
I am testing a set of 'T' (terrestrial frame camera) images with depth maps on v2.4. The depth maps are in MRF format with LERC compression. The distance measurement tool always shows 
 `NaNm ± NaN`.
<img src="https://drive.google.com/uc?export=view&id=1F728aRZlFogv0XG9acxEVVGbON7X8aNq" width="300px" />
Plus, Alt+Click does not seem to work. Red frustum disappears after zooming in by one level.

I can give you the data set in private messages.

**Comment by kushu493** [comment]
Hi Alex,

Can you please share the data so that we can reproduce the issue?

Thank you.

**Comment by SoftFeta** [comment]
Kushagra,
Sure. Send me an email @
mundanesurrealism~AT~gmail~DOT~com

**Comment by SoftFeta** [comment]
Fixed the issue. `a.imgrot` is missing.
In `groundToImageRM()` in `viewer.js`
Add `if (!a.imgrot) a.imgrot = 0;` after assignment of `a`:
```js
            var s = Math.PI / 180,
                a = this.selectedFeatureAttributes,
                r = [];
            if (!a.imgrot) a.imgrot = 0;
```
