### ISSUE TITLE
Can Oriented Imagery read `NoData` in MRF depth maps?

### ISSUE THREAD

**Issue by SoftFeta** [Esri/oriented-imagery#33]
Can Oriented Imagery read `NoData` in MRF depth maps?

**Comment by SoftFeta** [comment]
I am asking that because in many 3rd-party datasets, the **ground truth depth images** are have many dead pixels -- "datum is unavailable". 
There are many ways to fill these holes of course, one way is [greyscale erosion](https://en.wikipedia.org/wiki/Erosion_(morphology)#Grayscale_erosion).

**Comment by kushu493** [comment]
Yes. It can read NoData. PixelBlock will tell what's the value of NoData and distance for dead pixels is taken as 0.

**Comment by SoftFeta** [comment]
Thanks!
