### ISSUE TITLE
Floating-point MRF w/ LERC compression depth maps are correctly read, but the viewer is all black and measuring tools cannot be used

### ISSUE THREAD

**Issue by SoftFeta** [Esri/oriented-imagery#34]
I have some floating point MRF depth images with LERC compression.
The viewer is all black.
**I can see that `pixels: [Float32Array(2097152)]` are CORRECTLY loaded**. 
e.g. 
1010007: 29.698009490966797
1010008: 29.933534622192383
1010009: 29.933534622192383
1010010: 29.733535766601562

But the viewer is all black and measuring tools cannot be used.

**Comment by kushu493** [comment]
Can you share the sample with @abhiataero? I will look into it.

**Comment by kushu493** [comment]
Hi Alex,

I looked into it. The MRF files with LERC compression that you provided have issues. They are not encoded properly. I can't even load MRF file in ArcGIS Pro.

**Comment by SoftFeta** [comment]
If the file is corrupt, then why does the `pixels` array have correct values

**Comment by kushu493** [comment]
Pixels array also have wrong values. You can try to load the .lrc file with the sample app provided here. https://github.com/Esri/lerc
This is a lerc reader.

**Comment by SoftFeta** [comment]
I see, thanks!

**Comment by SoftFeta** [comment]
I know why the issue occurs now:
Under `addDepthValues()` in `viewer.js`:
```js
                    var d = t.statistics[0].minValue,
                        u = t.statistics[0].maxValue,
                        g = 255 / (u - d);
```
u happens to be `Infinity` for some reason, and `g` equals `0`

**Comment by SoftFeta** [comment]
Thanks Kushagra, the European dataset is all fixed now!
(The Brandenburg Gate is shown below)
<img src="https://drive.google.com/uc?export=view&id=16hDPTTHxUGvTIxNeo26-kdCqs2on0XaY" width="600px" />
