### ISSUE TITLE
Geospatial Video OIC

### ISSUE THREAD

**Issue by derrickocfa** [Esri/oriented-imagery#45]
Hello,

I am having trouble when trying to add geospatial video to my OIC.  I copied the GeospatialVideo.oictype and GeospatialVideo.py files to  C:\Image_Mgmt_Workflows\OrientedImagery\Types and I am able to see GeospatialVideo as an available Input Type in the Add Images to Oriented Imagery Catalog tool.  I have a .mp4 video file that I captured with a drone and was able to successfully combine with the corresponding geospatial video log using the Video Multiplexer tool.  I am able to view the video in the FMV Player and the geospatial components are displayed on my map so my video seems to have been properly multiplexed.  I have also uploaded the multiplexed video to my agency's public site so the video is web-accessible.

When I run the Add Images to Oriented Imagery Catalog tool:
-Input OIC is set to an empty OIC created by the Create Oriented Imagery Catalog tool
-Input Type is set to GeospatialVideo
-Metadata File is set to the path of the geospatial video log csv file (the same one I used for multiplexing) on my local drive
-Video File is set to the url for my multiplexed .mp4 video file on my agency's site
-Imagery Type is set to GeospatialVideo_Defaults
and the rest of the parameters are kept at their default values

This is where I'm stuck.  When running the tool, I receive the following message and I don't know how to proceed
![image](https://user-images.githubusercontent.com/17831636/113361845-c7b96b00-9301-11eb-9bbe-541f9ed63335.png)

The tool completes but it seems to have not done anything.  Any help is greatly appreciated!

On another note, I was wondering if there were plans to release any support documentation for Geospatial Video similar to the available user docs for Drone2Map, Pictometry, and Sanborn.

Thanks!

**Comment by RandallRebello** [comment]
HI Derrick, 
I just tested this and it works fine for me. 
This is the header and 1st line of the file I used.  Can you check against your file.  
If you are with it... you could send me copy of the file... I don't need the video file. I can debug here on my end. 

TimeStamp,UnixTimeStamp,SensorLatitude,SensorLongitude,PlatformHeading,PlatformPitch,PlatformRoll,SensorEllipsoidHeight,HorizontalFOV,VerticalFOV,SensorRelativeAzimuth,SensorRelativeElevation,SensorRelativeRoll
2020-10-13_11-52-40.557,1602615160557144,32.387481093,-117.076485785,55.20,-8.20,-4.40,19.26,73.74,53.13,354.67,6.71,3.87 

Randall

**Comment by RandallRebello** [comment]
@derrickocfa. I have also updated a user doc.

**Comment by derrickocfa** [comment]
Hi Randall,
Thanks for the reply and for uploading the user doc!  I believe my original issue was due to not having been logged into ArcGIS Online while running the Add Images to Oriented Imagery Catalog tool.  After signing in and then running the tool, I see that my Exposure Points table is now populated with records.  However, I'm encountering another issue as my Coverage Map table still remains empty.

After the Add Images tool runs, I see the following messages:
![image](https://user-images.githubusercontent.com/17831636/113933319-4baf9f00-97a9-11eb-80b6-6cb7b7785cf1.png)

As requested, here is my metadata file:
[DJI_0030.zip](https://github.com/Esri/oriented-imagery/files/6274458/DJI_0030.zip)

And here is the link to my video just in case it helps with further testing:
http://ocfa.org/_pfco/Dji 0030-1_Multiplex.mp4

By the way, I have downloaded and installed the newest release of the Oriented Imagery Management Tools (v2.6)

I really appreciate your help with this, thank you!

**Comment by RandallRebello** [comment]
@derrickocfa 
Thanks for sending me the sample file. I realize the problem. 
There is an extra line at the end of your sample file that is creating this issue. 
Open it up in the text editor (not excel) and delete the bottom most blank line. 

I'll work on a fix and update. Till then you can try it out by removing the line. 

>> However, I'm encountering another issue as my Coverage Map table still remains empty.
After adding the records.. run Create Coverage Features and then Create Coverage Map. 

Randall

**Comment by derrickocfa** [comment]
Hi @RandallRebello,
My bad about the coverage features and map.  I should have read ahead in the documentation!  I was able to generate them successfully.

I removed the carriage return from my metadata csv file but I'm still encountering the same issue:
![image](https://user-images.githubusercontent.com/17831636/114074736-8cff8780-9859-11eb-960b-80be2a5267fd.png)

When I try to view the OIC with the Oriented Imagery Viewer in Pro, the loading symbol appears but just hangs
![image](https://user-images.githubusercontent.com/17831636/114076487-938efe80-985b-11eb-82f3-c0f0bddbc450.png)

Do you think the issue could perhaps be with my video file?

Thanks,
Derrick

**Comment by kushu493** [comment]
Hi Derrick,

There is some issue with your video file. Even the browser cannot play the video. 

Thanks 
Kushagra

**Comment by derrickocfa** [comment]
Hi @kushu493,

Does the uploaded video file need to be the multiplexed video?  I was having trouble trying to get that file to play in the browser.  However, when I uploaded a copy of the video file that I had before multiplexing it, the video file plays just fine. 

I've tried running the Add Images to Oriented Imagery Catalog tool with the URL for the new video file but I still receive the 'Error in processing images.  list index out of range.' message
![image](https://user-images.githubusercontent.com/17831636/114599230-afbde180-9c47-11eb-9b54-dd35b84eebb0.png)

Here's the url to the new video file if it helps with testing:
https://ocfa.org/_pfco/Dji0030.mp4

I also double checked my csv to make sure the carriage return was removed just like @RandallRebello recommended.

Thank you!
Derrick

**Comment by kushu493** [comment]
Hi Derrick,

It worked now. I was able to view the video in Oriented imagery viewer.
See the link - https://oi1.img.arcgis.com/app/index.html?oic=80f3673b5c7c4d18b935891748b2d4ef

Try to create catalog using this .csv file
[DJI_0030.zip](https://github.com/Esri/oriented-imagery/files/6305941/DJI_0030.zip)

Thanks
Kushagra

**Comment by derrickocfa** [comment]
Hi Kushagra, thanks for getting back so quickly.  I tried the csv file you sent and still no luck being able to add images to the catalog successfully.  It's interesting that you're able to create one just fine on your end with the data I've provided when I'm unable to.  When you ran the Add Images to Oriented Imagery Catalog tool, did your parameters look different from this?

![image](https://user-images.githubusercontent.com/17831636/114623864-b149d280-9c64-11eb-8ca2-6f236bd7c02f.png)

Thanks,
Derrick

**Comment by kushu493** [comment]
Hi Derrick,
Apart from Frame Step which is 1 in my case, rest of the parameters are same. I tried with Frame step = 2, and still it worked. 

@RandallRebello can you please see why "Add images to Oriented Imagery tool" does not work for Derrick. Note - I am able to create OIC from the .csv file that I shared with Derrick. 

Thanks 
Kushagra

**Comment by RandallRebello** [comment]
Hi Derrick,
This is a bug in the code. It looks like the is a blank line at the end of your CSV file. You need to edit it in a text editor and remove this blank line.
I am working on a fix for it.
Randall

**Comment by derrickocfa** [comment]
Hi @RandallRebello,

I removed the blank line in my CSV a few days ago when you had originally brought it to my attention but I'm still receiving the "Error in processing images.  list index out of range" message.  I also tried the CSV that @kushu493 provided - which was used to successfully add the video to the OIC - but I still receive the same message when running the tool.  Is there something else that I could be missing that is causing Add Images to Oriented Imagery Catalog to not complete successfully?  I am on Pro v2.7.3 (though I was receiving the same error message at 2.7.2) and have installed the Oriented Imagery Management Tools (v2.6) and Oriented Imagery add-in for ArcGIS Pro (v2.6).  Thanks for your help!

-Derrick

**Comment by RandallRebello** [comment]
@derrickocfa Can you please check it now. I made a fix for this.

**Comment by derrickocfa** [comment]
@RandallRebello thank you for updating the python script, the tool completes successfully now!  Big thanks to you and @kushu493  for helping me with this!

PS - I'm not sure if you're the right person to notify for this but the OIC Viewer in ArcGIS Pro doesn't seem to want to play the video.  However, I was able to publish the OIC to ArcGIS Online and everything seems to be working in the OIC web app which was my goal all along.  Just thought I should let someone know

Thanks,
Derrick

**Comment by kushu493** [comment]
Hi Derrick,

Currently, we do not support video in ArcGIS Pro add-in tool. Video is currently only supported on the web.

Thanks,
Kushagra

**Comment by derrickocfa** [comment]
Hi Kushagra, 
It's funny that you mention that.  I found that when I converted the video file type to .webm, it will play in the OIC Viewer add-in tool in Pro.  I am, however, unable to play the video with the 2D widget in Web AppBuilder (neither .mp4 nor .webm will work).  The 3D version seems to work fine though.  I saw that 2D has been deprecated in lieu of support for an OIC widget in an upcoming release for ArcGIS Experience Builder.  Any chance you have an estimate for when that might become available?

Thanks,
Derrick

**Comment by kushu493** [comment]
Hi Derrick,

In OIC viewer add-in tool, we use chromium to display the viewer. Chromium does not support all the video codecs that google chrome supports. .webm format is supported by HTML as default. That's why it works.
2D widget is deprecated and has not been updated in past 2 years. Please don't use it to create apps.
Experience Builder widget will be released next week.

Thanks,
Kushagra

**Comment by abhiataero** [comment]
@derrickocfa  The Experience Builder Widget has been release. 
I am also closing this issue, i have created a new issue for supporting video in ArcGIS Pro Addin #53
