### ISSUE TITLE
Alt-clicking the picture does not correspond to the depth map

### ISSUE THREAD

**Issue by SoftFeta** [Esri/oriented-imagery#8]
Type of OIC: 'B'
The depth map in pannellum seems to be offset downwards that the location of the lime green diamond marker is incorrect.
<img src="https://drive.google.com/uc?export=view&id=1NrrtMleGpefG4j7XccxIlatVq454OQQJ" width="200px" />

**Comment by SoftFeta** [comment]
Measurement calculation does not take the depth map into account
except from applying the incorrect multiplication.

**Comment by SoftFeta** [comment]
It turns out that the projected width is incorrect.

**Comment by SoftFeta** [comment]
EDIT: The 817 is actually a variable related to the heading. Sometimes it's 700-something, others 900-something.

**Comment by SoftFeta** [comment]
Maybe I'll plot a graph later:
Heading Offset
130.88  0
127.65  21
67.03  367

**Comment by SoftFeta** [comment]
The parameters inserted into the `imageToGroundPanorama` functions are sheer incorrectness.

**Comment by priya4991** [comment]
@SoftFeta please update the widget with the new version and let us know if you face any issues.
Thanks!

**Comment by SoftFeta** [comment]
Fixed.
